# Generated by Django 3.1.3 on 2021-01-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(max_length=50),
        ),
    ]
