# Generated by Django 3.1.3 on 2021-01-07 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210107_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='edited_on',
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
